name: CI/CD for C++ VS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Visual Studio
        uses: microsoft/setup-msbuild@v2

      - name: Build solution
        run: |
          msbuild card2.sln /p:Configuration=Release

      - name: Run tests
        run: |
          cd C:\GitHub\card2
          card2.exe
      - name: Check build success
        run: echo "Build completed successfully!"